### ISSUE TITLE
Unknown flag on pull with clean el7 build

### ISSUE THREAD

**Issue by cs1867** [perfsonar/docker-oneshot-builder#1]
I built a new VM trying to create everything fresh.  When running oneshot I am getting an error.   
[1:25](https://perfsonar.slack.com/archives/D04RVJV1FFC/p1680629114990609)
[csacco@csacco-dev pscheduler]$ curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-builder/main/build | sh -s -  . el7
unknown flag: --pull
See 'docker run --help'.

**Comment by mfeit-internet2** [comment]
This was a result of the standard Docker on EL7 being old-enough that it doesn't have the `--pull` switch.

The default Podman has it, and I think that's the better choice anyway.
